name: Deploy to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create .env file
      run: |
        echo "${{secrets.ENV_FILE}}" > .env

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy Files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/home/replayslol-reddit-scraper/replayslol-reddit-commenter-api"

    - name: Set up Python Environment on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd replayslol-reddit-commenter-api
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  restart-uvicorn:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH and kill existing process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            PID=$(ps aux | grep "[r]eplayslol_reddit_commenter_api.main" | awk '{print $2}')
            if [ ! -z "$PID" ]; then
              echo "Process found. Killing process ID $PID."
              kill $PID
            else
              echo "Process not running."
            fi
      - name: SSH and start uvicorn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd replayslol-reddit-commenter-api
            source venv/bin/activate
            authbind --deep python3 -m src.replayslol_reddit_commenter_api.main &
            

